services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8001:8001"
    networks:
      - shared_network  # Добавлена сеть

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "81:81"
    depends_on:
      - django_gunicorn
    networks:
      - shared_network  # Добавлена сеть

volumes:
  static:

networks:
  shared_network:
    external: true
