name: Deploy Stack with Portainer

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Portainer redeploy
        uses: actions/github-script@v6
        with:
          script: |
            const fetch = require('node-fetch');

            // Аутентификация и получение токена
            const authResponse = await fetch('https://portainer.dev.payergate.com/api/auth', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                Username: autodeploy,
                Password: qweqwe123qweqwe123
              })
            });

            if (!authResponse.ok) {
              throw new Error(`Authentication failed: ${authResponse.statusText}`);
            }

            const authData = await authResponse.json();
            const token = authData.jwt;

            // Запрос на перезапуск стека
            const redeployResponse = await fetch('https://portainer.dev.payergate.com/api/stacks/29/git/redeploy?endpointId=2', {
              method: 'PUT',
              headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                prune: true,
                pullImage: true
              })
            });

            if (!redeployResponse.ok) {
              throw new Error(`Redeploy failed: ${redeployResponse.statusText}`);
            }

            console.log('Redeploy triggered successfully');
        
