name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u lampanykey --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lampanykey/anton:latest

      - name: Push the Docker image
        run: docker push lampanykey/anton:latest
